name: ci

on:
  push:
    branches:
      - main
      - next
      - 'v*'
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install
        run: npm i --ignore-scripts
      - name: run linter
        run: npm run lint

  test:
    permissions:
      contents: read
    strategy:
      matrix:
        version: [ 18, 20, 21 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: install
        run: npm i --ignore-scripts
      - name: test
        run: npm run test

